#!/usr/bin/env python3
"""
Convert PNG brand logos into an RGB565 C header for the ESP32 sketch.

Usage:
    pip install Pillow
    python3 convert_logos.py              # default 64x64
    python3 convert_logos.py --size 48

Place PNGs (transparent or solid background) in ../logos/ named after the
canonical brand slug — e.g. shell.png, bp.png, esso.png. Slugs must match
the ones the proxy emits in /cheapest → brand_slug. Run /brands on the
proxy to see which slugs cover the most stations.

The script writes ../petrol_station_display/logos.h containing:
    - one PROGMEM uint16_t[] per logo, RGB565
    - a BRAND_LOGOS table and lookupBrandLogo(slug) helper

The sketch #includes this file.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Install Pillow first: pip install Pillow")

# TFT background colour in RGB565 is 0x10A2 → RGB(16, 20, 16). Any transparent
# pixels in the source PNG are flattened onto this so the logo blends
# seamlessly with the screen background.
TFT_BG_RGB = (16, 20, 16)


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert_image(path: Path, size: int) -> list[int]:
    img = Image.open(path).convert("RGBA")
    bg = Image.new("RGBA", img.size, TFT_BG_RGB + (255,))
    flat = Image.alpha_composite(bg, img).convert("RGB")
    try:
        resample = Image.Resampling.LANCZOS
    except AttributeError:
        resample = Image.LANCZOS
    flat = flat.resize((size, size), resample)
    return [rgb565(r, g, b) for (r, g, b) in flat.getdata()]


def emit_array(name: str, data: list[int]) -> str:
    lines = [f"const uint16_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--size", type=int, default=64, help="Output square size in pixels (default 64)")
    parser.add_argument("--logos-dir", type=Path, default=here.parent / "logos")
    parser.add_argument("--output", type=Path,
                        default=here.parent / "petrol_station_display" / "logos.h")
    args = parser.parse_args()

    if not args.logos_dir.is_dir():
        sys.exit(f"Missing {args.logos_dir}. Put <slug>.png files there.")

    pngs = sorted(args.logos_dir.glob("*.png"))
    if not pngs:
        print(f"No PNGs in {args.logos_dir} — writing empty stub.", file=sys.stderr)

    header: list[str] = [
        "// AUTO-GENERATED by tools/convert_logos.py — do not edit by hand.",
        "// Brand logos are trademarks of their respective owners; this file is",
        "// generated locally for personal use on a single device.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"constexpr int BRAND_LOGO_SIZE = {args.size};",
        "",
    ]

    slugs: list[str] = []
    for png in pngs:
        slug = png.stem.lower().replace("-", "_")
        slugs.append(slug)
        print(f"  {png.name:30s} -> {slug} ({args.size}x{args.size})", file=sys.stderr)
        header.append(emit_array(f"LOGO_{slug}", convert_image(png, args.size)))
        header.append("")

    header.extend([
        "struct BrandLogo { const char* slug; const uint16_t* data; };",
        "",
        "constexpr BrandLogo BRAND_LOGOS[] = {",
    ])
    for slug in slugs:
        header.append(f'  {{"{slug}", LOGO_{slug}}},')
    header.extend([
        "};",
        "constexpr size_t BRAND_LOGO_COUNT = sizeof(BRAND_LOGOS) / sizeof(BRAND_LOGOS[0]);",
        "",
        "inline const uint16_t* lookupBrandLogo(const String& slug) {",
        "  if (slug.length() == 0) return nullptr;",
        "  for (size_t i = 0; i < BRAND_LOGO_COUNT; i++) {",
        "    if (slug == BRAND_LOGOS[i].slug) return BRAND_LOGOS[i].data;",
        "  }",
        "  return nullptr;",
        "}",
        "",
    ])

    args.output.write_text("\n".join(header))
    print(f"Wrote {args.output} ({len(slugs)} logos)", file=sys.stderr)


if __name__ == "__main__":
    main()
