#!/usr/bin/env python3
"""
Convert PNG brand logos into an RGB565 C header for the ESP32 sketch.

Usage:
    pip install Pillow
    python3 convert_logos.py                 # default max 128x64
    python3 convert_logos.py --max-w 100 --max-h 72

Place PNGs (transparent or solid background) in ../logos/ named after the
canonical brand slug — e.g. shell.png, bp.png, esso.png. Slugs must match
the ones the proxy emits in /cheapest → brand_slug.

Aspect ratio is preserved: each logo is downsized to fit within the given
max-width × max-height box without distortion. The actual rendered size
per logo is emitted in the header so the sketch can position it correctly.

The script writes ../petrol_station_display/logos.h containing:
    - one PROGMEM uint16_t[] per logo, RGB565
    - a BRAND_LOGOS table mapping slug → {data, width, height}
    - lookupBrandLogo(slug) helper

The sketch #includes this file.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Install Pillow first: pip install Pillow")

# TFT background colour in RGB565 is 0x10A2 → RGB(16, 20, 16). Any transparent
# pixels in the source PNG are flattened onto this so the logo blends with
# the screen background.
TFT_BG_RGB = (16, 20, 16)


def rgb565(r: int, g: int, b: int) -> int:
    # The TFT panel this project uses is wired in BGR colour order, so R and
    # B come out swapped at render time (yellow text reads as cyan, orange as
    # blue). Pre-swap R and B here so the cancellation lands on the display
    # as the original colours.
    return ((b & 0xF8) << 8) | ((g & 0xFC) << 3) | (r >> 3)


def convert_image(path: Path, max_w: int, max_h: int) -> tuple[list[int], int, int]:
    img = Image.open(path).convert("RGBA")
    bg = Image.new("RGBA", img.size, TFT_BG_RGB + (255,))
    flat = Image.alpha_composite(bg, img).convert("RGB")
    try:
        resample = Image.Resampling.LANCZOS
    except AttributeError:
        resample = Image.LANCZOS
    flat.thumbnail((max_w, max_h), resample)
    w, h = flat.size
    return [rgb565(r, g, b) for (r, g, b) in flat.getdata()], w, h


def emit_array(name: str, data: list[int]) -> str:
    lines = [f"const uint16_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--max-w", type=int, default=128, help="Max width in pixels (default 128)")
    parser.add_argument("--max-h", type=int, default=64, help="Max height in pixels (default 64)")
    parser.add_argument("--logos-dir", type=Path, default=here.parent / "logos")
    parser.add_argument("--output", type=Path,
                        default=here.parent / "petrol_station_display" / "logos.h")
    args = parser.parse_args()

    if not args.logos_dir.is_dir():
        sys.exit(f"Missing {args.logos_dir}. Put <slug>.png files there.")

    pngs = sorted(args.logos_dir.glob("*.png"))
    if not pngs:
        print(f"No PNGs in {args.logos_dir} — writing empty stub.", file=sys.stderr)

    header: list[str] = [
        "// AUTO-GENERATED by tools/convert_logos.py — do not edit by hand.",
        "// Brand logos are trademarks of their respective owners; this file is",
        "// generated locally for personal use on a single device.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct BrandLogo {",
        "  const char* slug;",
        "  const uint16_t* data;",
        "  uint16_t width;",
        "  uint16_t height;",
        "};",
        "",
    ]

    slugs: list[tuple[str, int, int]] = []
    for png in pngs:
        slug = png.stem.lower().replace("-", "_")
        data, w, h = convert_image(png, args.max_w, args.max_h)
        slugs.append((slug, w, h))
        print(f"  {png.name:30s} -> {slug:20s} {w}x{h}", file=sys.stderr)
        header.append(f"// {png.name} -> {w}x{h}")
        header.append(emit_array(f"LOGO_{slug}", data))
        header.append("")

    header.append("constexpr BrandLogo BRAND_LOGOS[] = {")
    for slug, w, h in slugs:
        header.append(f'  {{"{slug}", LOGO_{slug}, {w}, {h}}},')
    header.extend([
        "};",
        "constexpr size_t BRAND_LOGO_COUNT = sizeof(BRAND_LOGOS) / sizeof(BRAND_LOGOS[0]);",
        "",
        "inline const BrandLogo* lookupBrandLogo(const String& slug) {",
        "  if (slug.length() == 0) return nullptr;",
        "  for (size_t i = 0; i < BRAND_LOGO_COUNT; i++) {",
        "    if (slug == BRAND_LOGOS[i].slug) return &BRAND_LOGOS[i];",
        "  }",
        "  return nullptr;",
        "}",
        "",
    ])

    args.output.write_text("\n".join(header))
    print(f"Wrote {args.output} ({len(slugs)} logos)", file=sys.stderr)


if __name__ == "__main__":
    main()
