// Stub — regenerated by tools/convert_logos.py once you drop PNGs into
// hardware/logos/ and run the script. Without it, lookupBrandLogo always
// returns nullptr and the sketch falls back to the generic fuel-pump icon.
#pragma once
#include <Arduino.h>

struct BrandLogo {
  const char* slug;
  const uint16_t* data;
  uint16_t width;
  uint16_t height;
};

inline const BrandLogo* lookupBrandLogo(const String&) {
  return nullptr;
}
