// Stub — regenerated by tools/convert_logos.py once you drop PNGs into
// hardware/logos/ and run the script. Without it, lookupBrandLogo always
// returns nullptr and the sketch falls back to the generic fuel-pump icon.
#pragma once
#include <Arduino.h>

constexpr int BRAND_LOGO_SIZE = 64;

inline const uint16_t* lookupBrandLogo(const String&) {
  return nullptr;
}
